name: CI

on:
  push:
    branches: ["main"]
  pull_request:
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - system: x86_64-linux
            runner: ubuntu-latest
          - system: aarch64-linux
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v6
      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@main
        with:
          extra-conf: |
            sandbox = false

      - name: Setup Nix cache
        uses: DeterminateSystems/flakehub-cache-action@main
        with:
          use-gha-cache: "enabled"
          flakehub-flake-name: "sc2in/ZigMark"

      - name: Install omnix
        run: nix --accept-flake-config profile add nixpkgs#omnix

      - name: Configure permissions
        run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0 || true

      - name: Run CI
        run: om ci run --systems ${{ matrix.system }}

      - name: Build release artifact
        if: success()
        run: nix build .#zigmark-safe -o zigmark-release

      - name: Upload artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: zigmark-${{ matrix.system }}
          path: zigmark-release/
          retention-days: 7
